name: Revisi贸n de c贸gido
run-name: Revisi贸n de c贸digo 
on: [push]
jobs:
  checkstyle:
    name:  A continuaci贸n se va a revisar el c贸digo que acaba de subir a ${{ github.repository }}. Este proceso puede tardar un par de minutos...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          #reporter: github-pr-review
          level: warning