name: Revisi贸n de c贸digo
run-name: Revisi贸n de c贸digo 
on: [push]
jobs:
  checkstyle:
    name:  Para ver los resultados revise su commit desde la p谩gina principal del respositorio ${{ github.repository }} en Github.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning