name: Revisi贸n de c贸digo
run-name: Revisi贸n de c贸digo 
on: [push]
jobs:
  checkstyle:
    name: Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          checkstyle_version: 10.7.0
      - run: echo " Para ver los resultados vaya a revisar su commit desde la p谩gina principal del respositorio ${{ github.repository }} en Github."
